export const TOGGLE_UPLOAD = 'TOGGLE_UPLOAD'

export const TOGGLE_CREATE_DIRECTORY = 'TOGGLE_CREATE_DIRECTORY'

export const TOGGLE_DELETE_ELEMENT = 'TOGGLE_DELETE_ELEMENT'

export const TOGGLE_RENAME_ELEMENT = 'TOGGLE_RENAME_ELEMENT'

export const TOGGLE_DRAG_ENTER = 'TOGGLE_DRAG_ENTER'

export const UPLOAD_PERCENTAGE = 'UPLOAD_PERCENTAGE'

export const UPLOAD_COMPLETE = 'UPLOAD_COMPLETE'

export const TOGGLE_THEME_MODE = 'TOGGLE_THEME_MODE'
